groups:
    - developer
recipes:
    mac_os_x:
        - osxdefaults::set_computer_name
        - osxdefaults::menu_add_battery_percentage
        - osxdefaults::tap_to_click
        - osxdefaults::finder_unhide_home
        - osxdefaults::finder_disable_the_warning_before_emptying_the_trash
        - osxdefaults::finder_disable_the_warning_when_changing_a_file_extension
        - osxdefaults::finder_search_the_current_folder_by_default
attributes:
    git:
        name: Felipe Campos Clarke
        email: felipecamposclarke@gmail.com
        aliases:
            ci: commit
            st: status
    osxdefaults:
        computername: felipecamposclarke
    homebrewalt:
        apps:
            - git-extras
        cask_apps:
            - dropbox
            - evernote
            - virtualbox
            - vagrant
            - atom
            - vlc
