recipes:
    global:
        - applications::create_var_chef_cache
    mac_os_x:
        - homebrewalt::default
attributes:
    homebrewalt:
        taps:
            - homebrew/dupes
        cask_apps:
            - google-chrome
            - java
        cask_fonts:
            - inconsolata
