recipes:
    global:
        - applications::create_var_chef_cache
        - applications::postgresql
        - applications::mysql
        - applications::php56
        - dotfiles::gitconfig
    mac_os_x:
        - homebrewalt::default
        - nodejs::default
        - ruby_build
        - rbenv::system
        - applications::sublime_text_3
attributes:
    homebrewalt:
        apps:
            - git
            - git-flow
        cask_apps:
            - sequel-pro
            - sourcetree
    nodejs:
        apps:
            - bower
            - grunt
            - grunt-cli
            - gulp
            - yo
    rbenv:
        plugins:
            - name: rbenv-vars
            - git_url: https://github.com/sstephenson/rbenv-vars.git
        rubies: ['2.0.0-p481', '2.0.0-p576', '2.1.3']
        upgrade: head
        global: '2.1.3'
    php-apps:
        - composer
